package visao;

import com.formdev.flatlaf.FlatDarkLaf;
import controle.CompraControle;
import java.text.ParseException;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import modelo.Clientes;
import modelo.Compra;
import modelo.Pacote;
import utils.DataUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Home
 */
public class GerenciarCompra extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarCompra.class.getName());
    private CompraControle CompraC = new CompraControle();
    private DefaultTableModel TabelaCompras;
    /**
     * Creates new form GerenciarCompra
     */
    public GerenciarCompra() {
        initComponents();
        
        
     TabelaCompras = new DefaultTableModel(
                new Object[][]{},
                new String[]{"cod_compra", "forma_paga", "valor", "data_compra", "cod_cliente", "cod_pacote"}
        );
    

        TableCompras.setModel(TabelaCompras);
        carregarTabela();
        
         TableCompras.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int linha = TableCompras.getSelectedRow();
            if (linha >= 0) {
                CodCompraC.setText(TableCompras.getValueAt(linha, 0).toString());
                DataCompraC.setText(TableCompras.getValueAt(linha, 3).toString());
                ValorC.setText(TableCompras.getValueAt(linha, 2).toString());
                ClienteC.setText(TableCompras.getValueAt(linha, 4).toString());
                PacoteC.setText(TableCompras.getValueAt(linha, 5).toString());
                FormaPagamentoC.setSelectedItem(TableCompras.getValueAt(linha, 1).toString());
            }
        }
    
    });
    RemoverCompraB.addActionListener(e -> RemoverCompra());     
         
    }
                 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCompras = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        RegistrarCompraB = new javax.swing.JButton();
        RemoverCompraB = new javax.swing.JButton();
        AlterarCompraB = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ClienteC = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        PacoteC = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        CodCompraC = new javax.swing.JTextField();
        FormaPagamentoC = new javax.swing.JComboBox<>();
        DataCompraC = new javax.swing.JFormattedTextField();
        ValorC = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        TableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodCompra", "DataCompra", "Valor", "Cliente", "Pacote", "FormaPagamento"
            }
        ));
        jScrollPane1.setViewportView(TableCompras);

        RegistrarCompraB.setText("Inserir");
        RegistrarCompraB.addActionListener(this::RegistrarCompraBActionPerformed);

        RemoverCompraB.setText("Remover");

        AlterarCompraB.setText("Alterar");
        AlterarCompraB.addActionListener(this::AlterarCompraBActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(RegistrarCompraB, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                .addGap(159, 159, 159)
                .addComponent(RemoverCompraB, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                .addGap(170, 170, 170)
                .addComponent(AlterarCompraB, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(RegistrarCompraB)
                    .addComponent(RemoverCompraB)
                    .addComponent(AlterarCompraB)))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jLabel2.setText("Forma de Pagamento:");

        jLabel3.setText("Valor:");

        jLabel4.setText("DataCompra:");

        jLabel5.setText("Cliente:");

        jLabel6.setText("Pacote:");

        jLabel1.setText("CodCompra:");

        CodCompraC.addActionListener(this::CodCompraCActionPerformed);

        FormaPagamentoC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pix", "Crédito", "Débito", "Boleto" }));

        DataCompraC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        ValorC.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DataCompraC))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CodCompraC)))
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ClienteC, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(FormaPagamentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(PacoteC)
                        .addGap(67, 67, 67))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CodCompraC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(PacoteC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValorC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(FormaPagamentoC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ClienteC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DataCompraC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(373, 373, 373))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(398, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CodCompraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CodCompraCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CodCompraCActionPerformed

    private void AlterarCompraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarCompraBActionPerformed
        // TODO add your handling code here:
          if (TableCompras.getSelectedRow() < 0) {
        JOptionPane.showMessageDialog(null, "Selecione uma compra na tabela!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

    Clientes cli = new Clientes();
    cli.setCliCodigo(Integer.parseInt(ClienteC.getText()));

    Pacote pac = new Pacote();
    pac.setCodPacote(Integer.parseInt(PacoteC.getText()));

    Compra c = new Compra();
    c.setCodCompra(Integer.parseInt(CodCompraC.getText()));
    c.setFormaPagamento(FormaPagamentoC.getSelectedItem().toString());
    c.setValor(Double.parseDouble(ValorC.getText().replace(",", ".")));
    c.setDataCompra(DataCompraC.getText());
    c.setCodCliente(cli);
    c.setCodPacote(pac);

    String resultado = CompraC.alterarCompra(c);

    if (resultado.equals("alterado")) {
        JOptionPane.showMessageDialog(null, "Compra alterada com sucesso!");
        carregarTabela();
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao alterar: " + resultado, "Erro", JOptionPane.ERROR_MESSAGE);
    }  
    }//GEN-LAST:event_AlterarCompraBActionPerformed

    private void RegistrarCompraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrarCompraBActionPerformed
        // TODO add your handling code here:
    Clientes cli = new Clientes();
    cli.setCliCodigo(Integer.parseInt(ClienteC.getText()));
    
    Pacote pac = new Pacote();
    pac.setCodPacote(Integer.parseInt(PacoteC.getText()));
    
    Compra c = new Compra();
    c.setCodCompra(Integer.parseInt(CodCompraC.getText()));
    c.setFormaPagamento(FormaPagamentoC.getSelectedItem().toString());
    c.setValor(Double.parseDouble(ValorC.getText().replace(",", ".")));
    c.setDataCompra(DataCompraC.getText());
    c.setCodCliente(cli);
    c.setCodPacote(pac);

    String resultado = CompraC.inserirCompra(c); // ← salva no banco

    if (resultado.equals("inserido")) {
        JOptionPane.showMessageDialog(null, "Compra registrada com sucesso!");
        carregarTabela(); // ← atualiza a tabela
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao registrar: " + resultado, "Erro", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_RegistrarCompraBActionPerformed

    private void RemoverCompra() {
    if (TableCompras.getSelectedRow() < 0) {
        JOptionPane.showMessageDialog(null, "Selecione uma compra na tabela!", "Atenção", JOptionPane.WARNING_MESSAGE);
        return;
    }

  
    int cod = Integer.parseInt(CodCompraC.getText());
    String resultado = CompraC.deletarCompra(cod);

    if (resultado.equals("deletado")) {
        JOptionPane.showMessageDialog(null, "Compra removida com sucesso!");
        carregarTabela();
    } else {
        JOptionPane.showMessageDialog(null, "Erro ao remover: " + resultado, "Erro", JOptionPane.ERROR_MESSAGE);
    }
}
    
    
    private void carregarTabela() {

        TabelaCompras.setRowCount(0); // limpa tabela
        ArrayList<Compra> lista = CompraC.consultarCompra();

        if (lista == null) {
            JOptionPane.showMessageDialog(
                    null,
                    "Nenhum cliente encontrado!",
                    "Aviso",
                    JOptionPane.INFORMATION_MESSAGE
            );
            return;
        }
        
        for(Compra comp : lista){
             TabelaCompras.addRow(new Object[]{
             
                 comp.getCodCompra(),
                 comp.getFormaPagamento(),
                 comp.getValor(),
                 comp.getDataCompra(),
                 comp.getCodCliente().getCliCodigo(),
                 comp.getCodPacote().getCodPacote()           
             });
        }
        
    }
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        try{
          FlatDarkLaf.setup();
        }
        catch(Exception ex){
            ex.printStackTrace();
        
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new GerenciarCompra().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarCompraB;
    private javax.swing.JTextField ClienteC;
    private javax.swing.JTextField CodCompraC;
    private javax.swing.JFormattedTextField DataCompraC;
    private javax.swing.JComboBox<String> FormaPagamentoC;
    private javax.swing.JTextField PacoteC;
    private javax.swing.JButton RegistrarCompraB;
    private javax.swing.JButton RemoverCompraB;
    private javax.swing.JTable TableCompras;
    private javax.swing.JFormattedTextField ValorC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
