/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import com.formdev.flatlaf.FlatDarkLaf;
import controle.CidadeControle;
import controle.HotelControle;
import java.time.LocalDate;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Cidade;
import modelo.Hotel;
import utils.DataUtils;
import static utils.DataUtils.parseData;

/**
 *
 * @author Budrys
 */
public class GerenciarHotel extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarHotel.class.getName());
    private HotelControle hc = new HotelControle();
    private DefaultTableModel modeloTabela;

    /**
     * Creates new form GerenciarHotel
     */
    public GerenciarHotel() {
        initComponents();
        codHotel.setVisible(false);
        modeloTabela = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Código", "CNPJ", "Local", "Endereço", "Check-in", "Check-out", "Cidade"}
        );

        jTable1.setModel(modeloTabela);
        carregarCidade();
        carregarTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertButton = new javax.swing.JButton();
        AlterButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        codHotel = new javax.swing.JTextField();
        Local = new javax.swing.JTextField();
        Endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CNPJ = new javax.swing.JTextField();
        Checkin = new javax.swing.JFormattedTextField();
        Checkout = new javax.swing.JFormattedTextField();
        comboCidade = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Hoteis - SkyMilles");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "CNPJ", "Local", "Endereço", "Check-in", "Check-out", "Cidade"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        InsertButton.setText("Inserir");
        InsertButton.addActionListener(this::InsertButtonActionPerformed);

        AlterButton.setText("Alterar");
        AlterButton.addActionListener(this::AlterButtonActionPerformed);

        RemoveButton.setText("Remover");
        RemoveButton.addActionListener(this::RemoveButtonActionPerformed);

        jLabel1.setText("Gerenciar Hotel");

        jLabel3.setText("Local");

        jLabel4.setText("Endereco");

        jLabel5.setText("Check-in");

        jLabel6.setText("Check-out");

        jLabel7.setText("Cidade");

        jLabel8.setText("CNPJ");

        Checkin.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        Checkout.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 498, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Endereco)
                            .addComponent(Local, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 604, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(InsertButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AlterButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RemoveButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(Checkout, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(comboCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(Checkin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Local, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(codHotel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertButton)
                    .addComponent(AlterButton)
                    .addComponent(RemoveButton))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        try {
            // Validações básicas
            if (CNPJ.getText().trim().isEmpty() || Local.getText().trim().isEmpty()
                    || Endereco.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha CNPJ, Local e Endereço.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (comboCidade.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma cidade.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Hotel hotel = new Hotel();
            hotel.setCNPJ(CNPJ.getText().trim());
            hotel.setLocal(Local.getText().trim());
            hotel.setEndereco(Endereco.getText().trim());
            hotel.setCheckIn(parseData(Checkin.getText().trim()));
            hotel.setCheckOut(parseData(Checkout.getText().trim()));
            hotel.setCidade((Cidade) comboCidade.getSelectedItem());

            String resultado = hc.inserirHotel(hotel);

            if ("Inserido".equals(resultado)) {
                JOptionPane.showMessageDialog(this, "Hotel inserido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                carregarTabela();
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao inserir: " + resultado, "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            logger.severe(ex.getMessage());
        }
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void AlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterButtonActionPerformed
        try {
            if (codHotel.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecione um hotel na tabela para alterar.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (CNPJ.getText().trim().isEmpty() || Local.getText().trim().isEmpty()
                    || Endereco.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Preencha CNPJ, Local e Endereço.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            if (comboCidade.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(this, "Selecione uma cidade.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            Hotel hotel = new Hotel();
            hotel.setCodHotel(Integer.parseInt(codHotel.getText().trim()));
            hotel.setCNPJ(CNPJ.getText().trim());
            hotel.setLocal(Local.getText().trim());
            hotel.setEndereco(Endereco.getText().trim());
            hotel.setCheckIn(parseData(Checkin.getText().trim()));
            hotel.setCheckOut(parseData(Checkout.getText().trim()));
            hotel.setCidade((Cidade) comboCidade.getSelectedItem());

            String resultado = hc.alterarHotel(hotel);

            if ("Alterado".equals(resultado)) {
                JOptionPane.showMessageDialog(this, "Hotel alterado com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                carregarTabela();
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao alterar: " + resultado, "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            logger.severe(ex.getMessage());
        }
    }//GEN-LAST:event_AlterButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        try {
            if (codHotel.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Selecione um hotel na tabela para remover.", "Atenção", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int confirmacao = JOptionPane.showConfirmDialog(this,
                    "Tem certeza que deseja remover o hotel selecionado?",
                    "Confirmar Remoção",
                    JOptionPane.YES_NO_OPTION,
                    JOptionPane.QUESTION_MESSAGE);

            if (confirmacao != JOptionPane.YES_OPTION) {
                return;
            }

            int codigo = Integer.parseInt(codHotel.getText().trim());
            String resultado = hc.deletarHotel(codigo);

            if ("Deletado".equals(resultado)) {
                JOptionPane.showMessageDialog(this, "Hotel removido com sucesso!", "Sucesso", JOptionPane.INFORMATION_MESSAGE);
                carregarTabela();
                limparCampos();
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao remover: " + resultado, "Erro", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro inesperado: " + ex.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
            logger.severe(ex.getMessage());
        }
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();

        if (linha != -1) {
            //"Código", "CNPJ", "Local", "Endereço", "Check-in", "Check-out", "Cidade"
            codHotel.setText(jTable1.getValueAt(linha, 0).toString());
            CNPJ.setText(jTable1.getValueAt(linha, 1).toString());
            Local.setText(jTable1.getValueAt(linha, 2).toString());
            Endereco.setText(jTable1.getValueAt(linha, 3).toString());
            Checkin.setText(jTable1.getValueAt(linha,4).toString());
            Checkout.setText(jTable1.getValueAt(linha,5).toString());
            Cidade c = (Cidade) jTable1.getValueAt(linha, 6);
                comboCidade.setSelectedItem(c);

        }


    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new GerenciarHotel().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterButton;
    private javax.swing.JTextField CNPJ;
    private javax.swing.JFormattedTextField Checkin;
    private javax.swing.JFormattedTextField Checkout;
    private javax.swing.JTextField Endereco;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTextField Local;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JTextField codHotel;
    private javax.swing.JComboBox<Cidade> comboCidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        modeloTabela.setRowCount(0);
        ArrayList<Hotel> lista = hc.consultarHoteis();
        for (Hotel h : lista) {


            modeloTabela.addRow(new Object[]{
                h.getCodHotel(),
                h.getCNPJ(),
                h.getLocal(),
                h.getEndereco(),
                DataUtils.formatData(h.getCheckIn()),
                DataUtils.formatData(h.getCheckOut()),
                h.getCidade()
            });
        }
    }

    public void carregarCidade() {

        comboCidade.removeAllItems();

        CidadeControle controle = new CidadeControle();

        ArrayList<Cidade> lista = controle.consultarCidades();

        for (Cidade c : lista) {

            comboCidade.addItem(c);
        }

        comboCidade.setSelectedIndex(-1);
    }

    private void limparCampos() {
        codHotel.setText("");
        CNPJ.setText("");
        Local.setText("");
        Endereco.setText("");
        Checkin.setText("");
        Checkout.setText("");
        comboCidade.setSelectedIndex(-1);
        jTable1.clearSelection();
    }
}
