/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import com.formdev.flatlaf.FlatDarkLaf;
import controle.AeroportoControle;
import controle.VooControle;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Aeroporto;
import modelo.Voo;
import utils.DataUtils;

/**
 *
 * @author Budrys
 */
  

    public class GerenciarVoos extends javax.swing.JFrame {

        private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarVoos.class.getName());
        private VooControle vc = new VooControle();
        private DefaultTableModel modeloTabela;
        private SimpleDateFormat formatoData = new SimpleDateFormat("dd-MM-yyyy");
        private SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");

        /**
         * Creates new form GerenciarVoos
         */
        public GerenciarVoos() {
            initComponents();
            modeloTabela = new DefaultTableModel(
                    new Object[][]{},
                    new String[]{"Código", "Num voo", "Origem", "Destino", "Partida", "Hora", "Chegada", "Hora", "Avião", "Companhia"}
            );

            jTable1.setModel(modeloTabela);
            carregarOrigem();
            carregarDestino();
            carregarTabela();
        }

        /**
         * This method is called from within the constructor to initialize the
         * form. WARNING: Do NOT modify this code. The content of this method is
         * always regenerated by the Form Editor.
         */
        @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        codVoo = new javax.swing.JTextField();
        numVoo = new javax.swing.JTextField();
        aviao = new javax.swing.JTextField();
        companhia = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertButton = new javax.swing.JButton();
        AlterButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        dataChegada = new javax.swing.JFormattedTextField();
        dataPartida = new javax.swing.JFormattedTextField();
        horaChegada = new javax.swing.JFormattedTextField();
        horaPartida = new javax.swing.JFormattedTextField();
        comboOrigem = new javax.swing.JComboBox<>();
        comboDestino = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Voos - SkyMilles");

        jLabel1.setText("Gerenciar Voos");

        jLabel2.setText("Cod Voo");

        jLabel3.setText("Num voo");

        jLabel4.setText("Origem");

        jLabel5.setText("Destino");

        jLabel6.setText("Partida");

        jLabel7.setText("Chegada");

        jLabel8.setText("Avião");

        jLabel9.setText("Companhia");

        codVoo.addActionListener(this::codVooActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Num voo", "Origem", "Destino", "Partida", "Hora", "Chegada", "Hora", "Avião", "Companhia"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        InsertButton.setText("Inserir");
        InsertButton.addActionListener(this::InsertButtonActionPerformed);

        AlterButton.setText("Alterar");
        AlterButton.addActionListener(this::AlterButtonActionPerformed);

        RemoveButton.setText("Remover");
        RemoveButton.addActionListener(this::RemoveButtonActionPerformed);

        dataChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        dataPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        horaChegada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        horaPartida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getTimeInstance(java.text.DateFormat.SHORT))));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(numVoo))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(comboOrigem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(codVoo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(9, 9, 9))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(dataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(horaChegada, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                    .addComponent(horaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(comboDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(aviao, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(companhia))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19))))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(324, Short.MAX_VALUE)
                .addComponent(InsertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AlterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveButton)
                .addGap(319, 319, 319))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(jLabel8)
                    .addComponent(codVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aviao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel9)
                    .addComponent(numVoo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(companhia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaPartida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(dataChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(horaChegada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertButton)
                    .addComponent(AlterButton)
                    .addComponent(RemoveButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codVooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codVooActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codVooActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        System.out.println(dataChegada.getValue());
        System.out.println(horaChegada.getValue());
        AeroportoControle ac = new AeroportoControle();
        Date dataC = (Date) dataChegada.getValue();
        Date horaC = (Date) horaChegada.getValue();
        Date dataP = (Date) dataPartida.getValue();
        Date horaP = (Date) horaPartida.getValue();

        if (dataC == null || horaC == null || dataP == null || horaP == null) {
            JOptionPane.showMessageDialog(null, "Preencha data e hora corretamente");
            return;
        }

        LocalDate localDateC = dataC.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalTime localTimeC = horaC.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalTime();

        LocalDate localDateP = dataP.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

        LocalTime localTimeP = horaP.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalTime();

        LocalDateTime dataHoraChegada = LocalDateTime.of(localDateC, localTimeC);
        LocalDateTime dataHoraPartida = LocalDateTime.of(localDateP, localTimeP);

        // continuar lógica de salvar...
        Aeroporto aOrigem = (Aeroporto) comboOrigem.getSelectedItem();
        Aeroporto aDestino = (Aeroporto) comboDestino.getSelectedItem();

        Voo v = new Voo(Integer.parseInt(codVoo.getText()), numVoo.getText(), aOrigem, aDestino, dataHoraChegada, dataHoraPartida, aviao.getText(), companhia.getText());

        vc.inserirVoo(v);

        carregarOrigem();
        carregarDestino();
        carregarTabela();


    }//GEN-LAST:event_InsertButtonActionPerformed

    private void AlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterButtonActionPerformed
        try {
            LocalDate localDateC = DataUtils.parseData(dataChegada.getText());
            LocalTime localTimeC = LocalTime.parse(horaChegada.getText(), DataUtils.HORA);
            LocalDate localDateP = DataUtils.parseData(dataPartida.getText());
            LocalTime localTimeP = LocalTime.parse(horaPartida.getText(), DataUtils.HORA);

            LocalDateTime dataHoraChegada = LocalDateTime.of(localDateC, localTimeC);
            LocalDateTime dataHoraPartida = LocalDateTime.of(localDateP, localTimeP);

            int linha = jTable1.getSelectedRow();
            if (linha == -1) {
                JOptionPane.showMessageDialog(null, "Selecione um voo na tabela.");
                return;
            }

            Aeroporto aOrigem = (Aeroporto) comboOrigem.getSelectedItem();
            Aeroporto aDestino = (Aeroporto) comboDestino.getSelectedItem();
            System.out.println("numVoo: " + numVoo.getText());
System.out.println("codVoo: " + codVoo.getText());
            Voo v = new Voo(Integer.parseInt(codVoo.getText()), numVoo.getText(), aOrigem, aDestino, dataHoraChegada, dataHoraPartida, aviao.getText(), companhia.getText());

            VooControle vc = new VooControle();
            vc.alterarVoo(v);

            carregarTabela();
            carregarOrigem();
            carregarDestino();
            limparCampos();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Preencha data e hora corretamente");
        }
    }//GEN-LAST:event_AlterButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        vc.removerVoo(Integer.parseInt(codVoo.getText()));
        carregarTabela();
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int linha = jTable1.getSelectedRow();
        if (linha == -1 || jTable1.getValueAt(linha, 0) == null) {
        return;  // ✅ ignora linhas vazias ou cliques inválidos
    }
        codVoo.setText(jTable1.getValueAt(linha, 0).toString());
        numVoo.setText(jTable1.getValueAt(linha, 1).toString());
        Aeroporto aOrigem = (Aeroporto) jTable1.getValueAt(linha, 2);
        comboOrigem.setSelectedItem(aOrigem);
        Aeroporto aDestino = (Aeroporto) jTable1.getValueAt(linha, 3);
        comboDestino.setSelectedItem(aDestino);
        try {
            LocalDate dPartida = DataUtils.parseData(jTable1.getValueAt(linha, 4).toString());
            LocalTime hPartida = LocalTime.parse(jTable1.getValueAt(linha, 5).toString(), DataUtils.HORA);
            LocalDate dChegada = DataUtils.parseData(jTable1.getValueAt(linha, 6).toString());
            LocalTime hChegada = LocalTime.parse(jTable1.getValueAt(linha, 7).toString(), DataUtils.HORA);

            // Converter para Date para o setValue() do JFormattedTextField
            dataPartida.setValue(java.sql.Date.valueOf(dPartida));
            horaPartida.setValue(java.util.Date.from(hPartida.atDate(LocalDate.now()).atZone(ZoneId.systemDefault()).toInstant()));
            dataChegada.setValue(java.sql.Date.valueOf(dChegada));
            horaChegada.setValue(java.util.Date.from(hChegada.atDate(LocalDate.now()).atZone(ZoneId.systemDefault()).toInstant()));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao carregar data/hora: " + e.getMessage());
        }
        aviao.setText(jTable1.getValueAt(linha, 8).toString());
        companhia.setText(jTable1.getValueAt(linha, 9).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new GerenciarVoos().setVisible(true));

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterButton;
    private javax.swing.JButton InsertButton;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JTextField aviao;
    private javax.swing.JTextField codVoo;
    private javax.swing.JComboBox<Aeroporto> comboDestino;
    private javax.swing.JComboBox<Aeroporto> comboOrigem;
    private javax.swing.JTextField companhia;
    private javax.swing.JFormattedTextField dataChegada;
    private javax.swing.JFormattedTextField dataPartida;
    private javax.swing.JFormattedTextField horaChegada;
    private javax.swing.JFormattedTextField horaPartida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField numVoo;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        modeloTabela.setRowCount(0);

        AeroportoControle cc = new AeroportoControle();
        ArrayList<Voo> lista = vc.consultarVoos();
        for (Voo v : lista) {
            LocalDateTime partida = v.getDataHoraPartida();

            Aeroporto aOrigem = cc.consultarAeroportoCodigo(v.getAeroPartida().getCodAeroporto());
            Aeroporto aDestino = cc.consultarAeroportoCodigo(v.getAeroDestino().getCodAeroporto());
            modeloTabela.addRow(new Object[]{
                v.getCodVoo(),
                v.getNumVoo(),
                v.getAeroPartida(),
                v.getAeroDestino(),
                DataUtils.formatData(v.getDataHoraPartida().toLocalDate()),
                DataUtils.formatHora(v.getDataHoraPartida().toLocalTime()),
                DataUtils.formatData(v.getDataHoraChegada().toLocalDate()),
                DataUtils.formatHora(v.getDataHoraChegada().toLocalTime()),
                v.getAviao(),
                v.getCompanhia()
            });
        }
    }

    public void carregarOrigem() {

        comboOrigem.removeAllItems();

        AeroportoControle controle = new AeroportoControle();

        ArrayList<Aeroporto> lista = controle.consultarAeroportos();

        for (Aeroporto a : lista) {

            comboOrigem.addItem(a);
        }

        comboOrigem.setSelectedIndex(-1);
    }

    public void carregarDestino() {

        comboDestino.removeAllItems();

        AeroportoControle controle = new AeroportoControle();

        ArrayList<Aeroporto> lista = controle.consultarAeroportos();

        for (Aeroporto a : lista) {

            comboDestino.addItem(a);
        }

        comboDestino.setSelectedIndex(-1);
    }

    public void limparCampos() {

        codVoo.setText("");

        numVoo.setText("");

        comboOrigem.setSelectedIndex(-1);

        comboDestino.setSelectedIndex(-1);

        dataPartida.setText("");

        horaPartida.setText("");

        dataChegada.setText("");

        horaChegada.setText("");

        aviao.setText("");

        companhia.setText("");
    }

    private void formWindowActivated(
            java.awt.event.WindowEvent evt
    ) {

        carregarOrigem();
        carregarDestino();
    }

}
