/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import com.formdev.flatlaf.FlatDarkLaf;
import controle.ClientesControle;
import controle.UsuarioControle;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Clientes;
import modelo.Usuario;

/**
 *
 * @author Budrys
 */
public class GerenciarUsuario extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarUsuario.class.getName());
    private UsuarioControle uc = new UsuarioControle();
    private DefaultTableModel modeloTabela;

    /**
     * Creates new form GerenciarUsuario
     */
    public GerenciarUsuario() {
        initComponents();
        codUsuario.setVisible(false);
        modeloTabela = new DefaultTableModel(
                new Object[][]{},
                new String[]{"Código", "Login", "Senha", "E-mail", "Cliente"}
        );

        jTable1.setModel(modeloTabela);
        carregarTabela();
        carregarClientes();
        Cliente.setSelectedIndex(-1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        codUsuario = new javax.swing.JTextField();
        Login = new javax.swing.JTextField();
        Senha = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        InsertButton = new javax.swing.JButton();
        AlterButton = new javax.swing.JButton();
        RemoveButton = new javax.swing.JButton();
        Cliente = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Usuários - SkyMilles");

        jLabel2.setText("Login");

        jLabel3.setText("Senha");

        jLabel4.setText("E-mail");

        jLabel5.setText("Cliente");

        jLabel6.setText("Gerenciar Usuário");

        codUsuario.addActionListener(this::codUsuarioActionPerformed);

        email.addActionListener(this::emailActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Código", "Login", "Senha", "E-mail", "Cliente"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        InsertButton.setText("Inserir");
        InsertButton.addActionListener(this::InsertButtonActionPerformed);

        AlterButton.setText("Alterar");
        AlterButton.addActionListener(this::AlterButtonActionPerformed);

        RemoveButton.setText("Remover");
        RemoveButton.addActionListener(this::RemoveButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Senha))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(15, 15, 15)
                                .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(137, 137, 137)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(email))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(codUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(64, 64, 64))
            .addComponent(jScrollPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(284, Short.MAX_VALUE)
                .addComponent(InsertButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(AlterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RemoveButton)
                .addGap(280, 280, 280))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(Senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(codUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsertButton)
                    .addComponent(AlterButton)
                    .addComponent(RemoveButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void codUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codUsuarioActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void AlterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterButtonActionPerformed
        int linha = jTable1.getSelectedRow();

        if (linha == -1) {
            JOptionPane.showMessageDialog(null, "Selecione um usuário na tabela.");
            return;
        }
        Clientes cli = (Clientes) Cliente.getSelectedItem();

        Usuario usu = new Usuario(Integer.parseInt(codUsuario.getText()), Login.getText(), Senha.getText(), email.getText(), cli);

        UsuarioControle uc = new UsuarioControle();
        uc.alterarUsuario(usu);

        carregarTabela();

        limparCampos();

        Cliente.setSelectedIndex(-1);

        codUsuario.setEditable(true);

        Cliente.setEnabled(true);
    }//GEN-LAST:event_AlterButtonActionPerformed

    private void InsertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InsertButtonActionPerformed
        UsuarioControle uc = new UsuarioControle();
        //int usuCodigo, String usuLogin, String usuSenha, String usuEmail, Clientes usuCliente
        Clientes cli = (Clientes) Cliente.getSelectedItem();
        if (Cliente.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(null,
                    "Selecione um cliente");
            return;
        }
        Usuario u = new Usuario(Login.getText(), Senha.getText(), email.getText(), cli);
        uc.inserirUsuario(u);
        carregarTabela();
    }//GEN-LAST:event_InsertButtonActionPerformed

    private void RemoveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveButtonActionPerformed
        UsuarioControle uc = new UsuarioControle();
     
            uc.deletarUsuario(Integer.parseInt(codUsuario.getText()));
            carregarTabela();
    }//GEN-LAST:event_RemoveButtonActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        codUsuario.setEditable(false);
        Cliente.setEditable(false);
        int linha = jTable1.getSelectedRow();
        codUsuario.setText(jTable1.getValueAt(linha, 0).toString());
        Login.setText(jTable1.getValueAt(linha, 1).toString());
        Senha.setText(jTable1.getValueAt(linha, 2).toString());
        email.setText(jTable1.getValueAt(linha, 3).toString());

        Clientes cli = (Clientes) jTable1.getValueAt(linha, 4);
        Cliente.setSelectedItem(cli);
    }//GEN-LAST:event_jTable1MouseClicked

        /**
         * @param args the command line arguments
         */
        public static void main(String args[]) {
            try {
                FlatDarkLaf.setup();
            } catch (Exception ex) {
                ex.printStackTrace();
            }

            java.awt.EventQueue.invokeLater(() -> new GerenciarUsuario().setVisible(true));
        }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterButton;
    private javax.swing.JComboBox<Clientes> Cliente;
    private javax.swing.JButton InsertButton;
    private javax.swing.JTextField Login;
    private javax.swing.JButton RemoveButton;
    private javax.swing.JTextField Senha;
    private javax.swing.JTextField codUsuario;
    private javax.swing.JTextField email;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void carregarTabela() {
        modeloTabela.setRowCount(0);
        ClientesControle cc = new ClientesControle();
        ArrayList<Usuario> lista = uc.consultarUsuarios();
        for (Usuario u : lista) {

            Clientes cliente = cc.consultarClienteCodigo(u.getUsuCliente().getCliCodigo());

            modeloTabela.addRow(new Object[]{
                u.getUsuCodigo(),
                u.getUsuLogin(),
                u.getUsuSenha(),
                u.getUsuEmail(),
                u.getUsuCliente()
            });
        }

    }

    public void carregarClientes() {

        Cliente.removeAllItems();

        ClientesControle controle = new ClientesControle();

        ArrayList<Clientes> lista = controle.consultarClientes();

        for (Clientes cli : lista) {

            Cliente.addItem(cli);
        }

        Cliente.setSelectedIndex(-1);
    }

    public void limparCampos() {

        codUsuario.setText("");

        Login.setText("");

        Senha.setText("");

        email.setText("");

        Cliente.setSelectedIndex(-1);

        codUsuario.setEditable(true);

        Cliente.setEnabled(true);
    }

    private void formWindowActivated(
            java.awt.event.WindowEvent evt
    ) {

        carregarClientes();
    }
}
