/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

import com.formdev.flatlaf.FlatDarkLaf;
import controle.AssentosControle;

/**
 *
 * @author Home
 */
public class GerenciarAssentos extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GerenciarAssentos.class.getName());

    /**
     * Creates new form AssentosGUI
     */
   public GerenciarAssentos() {
    initComponents();
    
    // Evento de clique na tabela
    TableAss.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            int linha = TableAss.getSelectedRow();
            if (linha >= 0) {
                CampoCodAss.setText(TableAss.getValueAt(linha, 0).toString());
                CampoNumBilheteAss.setText(TableAss.getValueAt(linha, 1).toString());
                CampoDataEmissaoAss.setText(TableAss.getValueAt(linha, 2).toString());
                CampoClasseAss.setSelectedItem(TableAss.getValueAt(linha, 3).toString());
                CampoValorAss.setText(TableAss.getValueAt(linha, 4).toString());
                CampoStatusAss.setSelectedItem(TableAss.getValueAt(linha, 5).toString());
                CampoPacoteAss.setText(TableAss.getValueAt(linha, 6).toString());
                CampoCodDestinoAss.setText(TableAss.getValueAt(linha, 7).toString());
                CampoCodLocalPartidaAss.setText(TableAss.getValueAt(linha, 8).toString());
                CampoCodVooAss.setText(TableAss.getValueAt(linha, 9).toString());
            }
        }
    });

    // Liga os botões aos métodos
    BtnAddAssento.addActionListener(e -> adicionarAssento());
    BtnRmvAssento.addActionListener(e -> removerAssento());
    BtnAlterarAssento.addActionListener(e -> alterarAssento());
    BtnConsultarAssentos.addActionListener(e -> consultarAssentos());
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollBar1 = new javax.swing.JScrollBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableAss = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CampoCodAss = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        CampoNumBilheteAss = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        CampoDataEmissaoAss = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CampoClasseAss = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        CampoValorAss = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        CampoCodDestinoAss = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        CampoPacoteAss = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        CampoStatusAss = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        CampoCodVooAss = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        CampoCodLocalPartidaAss = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        BtnAddAssento = new javax.swing.JButton();
        BtnRmvAssento = new javax.swing.JButton();
        BtnAlterarAssento = new javax.swing.JButton();
        BtnConsultarUMAssento = new javax.swing.JButton();
        BtnConsultarAssentos = new javax.swing.JButton();

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Assentos - SkyMilles");

        TableAss.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CodAssento", "NumBilhete", "DataEmissão", "Classe", "ValorAss", "Status", "PacoteAssento  ", "CodDestino ", "CodLocalPartida  ", "CodVoo "
            }
        ));
        jScrollPane1.setViewportView(TableAss);

        jButton2.setText("X");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jLabel2.setText("CodAssento:");

        jLabel3.setText("NumBilhete:");

        jLabel4.setText("dataEmissao:");

        jLabel5.setText("Classe:");

        CampoClasseAss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "E" }));

        jLabel7.setText("ValorAss:");

        jLabel10.setText("codDestino:");

        CampoCodDestinoAss.addActionListener(this::CampoCodDestinoAssActionPerformed);

        jLabel9.setText("PacoteAssento:");

        jLabel8.setText("Status:");

        CampoStatusAss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "0" }));
        CampoStatusAss.addActionListener(this::CampoStatusAssActionPerformed);

        jLabel12.setText("codVoo:");

        jLabel11.setText("codLocalPartida:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoCodAss, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoNumBilheteAss, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(CampoDataEmissaoAss))))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoPacoteAss, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CampoCodLocalPartidaAss, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CampoCodDestinoAss, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel12))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CampoClasseAss, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(CampoValorAss, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel8)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CampoCodVooAss, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CampoStatusAss, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, jLabel2, jLabel3, jLabel4, jLabel5, jLabel9});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CampoCodAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(CampoClasseAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(CampoPacoteAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(CampoCodLocalPartidaAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(CampoNumBilheteAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(CampoValorAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(CampoStatusAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(CampoDataEmissaoAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(CampoCodDestinoAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(CampoCodVooAss, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel10, jLabel11, jLabel12, jLabel2, jLabel3, jLabel4, jLabel5, jLabel7, jLabel8, jLabel9});

        BtnAddAssento.setBackground(new java.awt.Color(51, 255, 51));
        BtnAddAssento.setText("AddAssento");
        BtnAddAssento.addActionListener(this::BtnAddAssentoActionPerformed);

        BtnRmvAssento.setBackground(new java.awt.Color(255, 0, 51));
        BtnRmvAssento.setText("RemoverAssento");

        BtnAlterarAssento.setBackground(new java.awt.Color(204, 0, 204));
        BtnAlterarAssento.setText("AlterarAssento");

        BtnConsultarUMAssento.setBackground(new java.awt.Color(255, 153, 51));
        BtnConsultarUMAssento.setText("ConsultarUMAssento");
        BtnConsultarUMAssento.addActionListener(this::BtnConsultarUMAssentoActionPerformed);

        BtnConsultarAssentos.setBackground(new java.awt.Color(51, 153, 255));
        BtnConsultarAssentos.setText("ConsultarAssentos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BtnAddAssento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnRmvAssento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnAlterarAssento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnConsultarUMAssento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnConsultarAssentos)
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BtnAddAssento, BtnAlterarAssento, BtnConsultarAssentos, BtnConsultarUMAssento, BtnRmvAssento});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnAddAssento)
                    .addComponent(BtnRmvAssento)
                    .addComponent(BtnAlterarAssento)
                    .addComponent(BtnConsultarUMAssento)
                    .addComponent(BtnConsultarAssentos, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BtnAddAssento, BtnAlterarAssento, BtnConsultarAssentos, BtnConsultarUMAssento, BtnRmvAssento});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(270, 270, 270)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1378, 1378, 1378))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1203, 1203, 1203)))))
                        .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel6))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 37, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnConsultarUMAssentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnConsultarUMAssentoActionPerformed
  
      if (CampoCodAss.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o CodAssento!", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String sql = "SELECT cod_assento, num_bilhete, data_emissao, _classe, valor_ass, _status, cod_pacote, cod_destino, cod_local_partida, cod_voo FROM Assento WHERE cod_assento = ?";

    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TableAss.getModel();
    modelo.setRowCount(0);

    conexao.ConexaoMySQLSky conn_obj = new conexao.ConexaoMySQLSky();

    try (java.sql.Connection conn = conn_obj.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, Integer.parseInt(CampoCodAss.getText()));

        try (java.sql.ResultSet rs = ps.executeQuery()) {
            if (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("cod_assento"),
                    rs.getInt("num_bilhete"),
                    rs.getString("data_emissao"),
                    rs.getString("_classe"),
                    rs.getDouble("valor_ass"),
                    rs.getBoolean("_status") ? "1" : "0",
                    rs.getInt("cod_pacote"),
                    rs.getInt("cod_destino"),
                    rs.getInt("cod_local_partida"),
                    rs.getInt("cod_voo")
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Assento não encontrado!");
            }
        }

    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
    }
        
    }//GEN-LAST:event_BtnConsultarUMAssentoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void CampoStatusAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoStatusAssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoStatusAssActionPerformed

    private void CampoCodDestinoAssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CampoCodDestinoAssActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CampoCodDestinoAssActionPerformed

    private void BtnAddAssentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAddAssentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAddAssentoActionPerformed

    
    private conexao.ConexaoMySQLSky conexao = new conexao.ConexaoMySQLSky();

private void limparCampos() {
    CampoCodAss.setText("");
    CampoNumBilheteAss.setText("");
    CampoDataEmissaoAss.setText("");
    CampoValorAss.setText("");
    CampoCodDestinoAss.setText("");
    CampoPacoteAss.setText("");
    CampoCodLocalPartidaAss.setText("");
    CampoCodVooAss.setText("");
    CampoClasseAss.setSelectedIndex(0);
    CampoStatusAss.setSelectedIndex(0);
    TableAss.clearSelection();
}

private void consultarAssentos() {
    String sql = "SELECT cod_assento, num_bilhete, data_emissao, _classe, valor_ass, _status, cod_pacote, cod_destino, cod_local_partida, cod_voo FROM Assento";

    javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) TableAss.getModel();
    modelo.setRowCount(0);

    try (java.sql.Connection conn = conexao.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql);
         java.sql.ResultSet rs = ps.executeQuery()) {

        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getInt("cod_assento"),
                rs.getInt("num_bilhete"),
                rs.getString("data_emissao"),
                rs.getString("_classe"),
                rs.getDouble("valor_ass"),
                rs.getBoolean("_status") ? "1" : "0",
                rs.getInt("cod_pacote"),
                rs.getInt("cod_destino"),
                rs.getInt("cod_local_partida"),
                rs.getInt("cod_voo")
            });
        }

    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
    }
}

private void adicionarAssento() {
    if (CampoNumBilheteAss.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Informe o Número do Bilhete!", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    // ↓ VERIFICAÇÃO SE JÁ EXISTE - ADICIONA ESSE BLOCO
  String sqlVerifica = "SELECT COUNT(*) FROM Assento WHERE num_bilhete = ? AND cod_assento = ?";
    try (java.sql.Connection conn = conexao.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sqlVerifica)) {

        ps.setInt(1, Integer.parseInt(CampoNumBilheteAss.getText()));
        ps.setInt(2, Integer.parseInt(CampoCodAss.getText()));
        java.sql.ResultSet rs = ps.executeQuery();

        if (rs.next() && rs.getInt(1) > 0) {
            // Se COUNT retornou mais que 0, já existe
            javax.swing.JOptionPane.showMessageDialog(this, 
                "Esse Número de Bilhete já está cadastrado!", 
                "Atenção", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return; // Para aqui, não insere
        }

    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro ao verificar: " + ex.getMessage());
        return;
    }
    // ↑ ATÉ AQUI

    // Se passou da verificação, aí insere normalmente
    String sql = "INSERT INTO Assento (num_bilhete, data_emissao, _classe, valor_ass, _status, cod_pacote, cod_destino, cod_local_partida, cod_voo) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)";

    try (java.sql.Connection conn = conexao.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, Integer.parseInt(CampoNumBilheteAss.getText()));
        ps.setString(2, CampoDataEmissaoAss.getText());
        ps.setString(3, CampoClasseAss.getSelectedItem().toString());
        ps.setDouble(4, Double.parseDouble(CampoValorAss.getText()));
        ps.setBoolean(5, CampoStatusAss.getSelectedItem().toString().equals("1"));
        ps.setInt(6, Integer.parseInt(CampoPacoteAss.getText()));
        ps.setInt(7, Integer.parseInt(CampoCodDestinoAss.getText()));
        ps.setInt(8, Integer.parseInt(CampoCodLocalPartidaAss.getText()));
        ps.setInt(9, Integer.parseInt(CampoCodVooAss.getText()));

        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Assento adicionado!");
        limparCampos();
        consultarAssentos();

    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
    }
}

private void removerAssento() {
    if (TableAss.getSelectedRow() < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um assento na tabela!", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, "Deseja remover?", "Confirmar", javax.swing.JOptionPane.YES_NO_OPTION);
    if (confirm != javax.swing.JOptionPane.YES_OPTION) return;

    String sql = "DELETE FROM Assento WHERE cod_assento = ?";

    try (java.sql.Connection conn = conexao.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, Integer.parseInt(CampoCodAss.getText()));
        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Assento removido!");
        limparCampos();
        consultarAssentos();

    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
    }
}

private void alterarAssento() {
    if (TableAss.getSelectedRow() < 0) {
        javax.swing.JOptionPane.showMessageDialog(this, "Selecione um assento na tabela!", "Atenção", javax.swing.JOptionPane.WARNING_MESSAGE);
        return;
    }

    String sql = "UPDATE Assento SET num_bilhete=?, data_emissao=?, _classe=?, valor_ass=?, _status=?, cod_pacote=?, cod_destino=?, cod_local_partida=?, cod_voo=? WHERE cod_assento=?";

    try (java.sql.Connection conn = conexao.conectar();
         java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

        ps.setInt(1, Integer.parseInt(CampoNumBilheteAss.getText()));
        ps.setString(2, CampoDataEmissaoAss.getText());
        ps.setString(3, CampoClasseAss.getSelectedItem().toString());
        ps.setDouble(4, Double.parseDouble(CampoValorAss.getText()));
        ps.setBoolean(5, CampoStatusAss.getSelectedItem().toString().equals("1"));
        ps.setInt(6, Integer.parseInt(CampoPacoteAss.getText()));
        ps.setInt(7, Integer.parseInt(CampoCodDestinoAss.getText()));
        ps.setInt(8, Integer.parseInt(CampoCodLocalPartidaAss.getText()));
        ps.setInt(9, Integer.parseInt(CampoCodVooAss.getText()));
        ps.setInt(10, Integer.parseInt(CampoCodAss.getText()));

        ps.executeUpdate();
        javax.swing.JOptionPane.showMessageDialog(this, "Assento alterado!");
        limparCampos();
        consultarAssentos();

    } catch (java.sql.SQLException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + ex.getMessage());
    }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        try {
            FlatDarkLaf.setup();
        } catch (Exception ex) {
            ex.printStackTrace();
        }

        java.awt.EventQueue.invokeLater(() -> new GerenciarAssentos().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAddAssento;
    private javax.swing.JButton BtnAlterarAssento;
    private javax.swing.JButton BtnConsultarAssentos;
    private javax.swing.JButton BtnConsultarUMAssento;
    private javax.swing.JButton BtnRmvAssento;
    private javax.swing.JComboBox<String> CampoClasseAss;
    private javax.swing.JTextField CampoCodAss;
    private javax.swing.JTextField CampoCodDestinoAss;
    private javax.swing.JTextField CampoCodLocalPartidaAss;
    private javax.swing.JTextField CampoCodVooAss;
    private javax.swing.JTextField CampoDataEmissaoAss;
    private javax.swing.JTextField CampoNumBilheteAss;
    private javax.swing.JTextField CampoPacoteAss;
    private javax.swing.JComboBox<String> CampoStatusAss;
    private javax.swing.JTextField CampoValorAss;
    private javax.swing.JTable TableAss;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollBar jScrollBar1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
